apply plugin: 'com.android.application'

android {
    namespace 'com.example.musicplayer50'

    compileSdk 35

    defaultConfig {
        applicationId "com.example.musicplayer50"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    testImplementation 'junit:junit:4.13.2'

    implementation 'com.android.support:appcompat-v7:24.2.1'
}
